// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGsIEzC9TV-sbN1SntNMCQd3KAtpyLXuo',
    appId: '1:219537353975:web:8327d1305f1b18d5c737f2',
    messagingSenderId: '219537353975',
    projectId: 'tripsync-b66b0',
    authDomain: 'tripsync-b66b0.firebaseapp.com',
    storageBucket: 'tripsync-b66b0.firebasestorage.app',
    measurementId: 'G-W73RHHE7FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAngrfRA86UDV77W_Cc-Xzj99FxPPd6r2s',
    appId: '1:219537353975:android:870376d75df0d6dec737f2',
    messagingSenderId: '219537353975',
    projectId: 'tripsync-b66b0',
    storageBucket: 'tripsync-b66b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBdQyyz7fIxN2fcwDn4ayvv1ccrunQqLU',
    appId: '1:219537353975:ios:c80de838b5c635a6c737f2',
    messagingSenderId: '219537353975',
    projectId: 'tripsync-b66b0',
    storageBucket: 'tripsync-b66b0.firebasestorage.app',
    iosBundleId: 'com.example.tripsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBdQyyz7fIxN2fcwDn4ayvv1ccrunQqLU',
    appId: '1:219537353975:ios:c80de838b5c635a6c737f2',
    messagingSenderId: '219537353975',
    projectId: 'tripsync-b66b0',
    storageBucket: 'tripsync-b66b0.firebasestorage.app',
    iosBundleId: 'com.example.tripsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGsIEzC9TV-sbN1SntNMCQd3KAtpyLXuo',
    appId: '1:219537353975:web:c33ae31c4c8031aac737f2',
    messagingSenderId: '219537353975',
    projectId: 'tripsync-b66b0',
    authDomain: 'tripsync-b66b0.firebaseapp.com',
    storageBucket: 'tripsync-b66b0.firebasestorage.app',
    measurementId: 'G-2HSSB9DY2B',
  );

}